export const categories = [
  { id: 0, name: "All Category" },
  { id: 1, name: "Electronics" },
  { id: 2, name: "Computer" },
  { id: 3, name: "Smart Home" },
  { id: 4, name: "Automotive" },
  { id: 5, name: "Baby" },
  { id: 6, name: "Beauty" },
  { id: 7, name: "Personal Care" },
  { id: 8, name: "Butcher Shop" },
  { id: 9, name: "Cafe" },
  { id: 10, name: "Charity" },
  { id: 11, name: "Church" },
  { id: 12, name: "Clinic" },
  { id: 13, name: "College" },
  { id: 14, name: "Conference" },
  { id: 15, name: "Construction" },
  { id: 16, name: "Corona Virus" },
  { id: 17, name: "Corporate" },
  { id: 18, name: "Covid19" },
  { id: 19, name: "Digital Products" },
  { id: 20, name: "Doctors" },
  { id: 21, name: "Ecological" },
  { id: 22, name: "Education" },
  { id: 23, name: "Entertainment" },
  { id: 24, name: "Environment" },
  { id: 25, name: "Environmental" },
  { id: 26, name: "Events" },
  { id: 27, name: "Fitness" },
  { id: 28, name: "Food Shop" },
  { id: 29, name: "Free" },
  { id: 30, name: "Gym" },
  { id: 31, name: "Halloween" },
  { id: 32, name: "Health" },
  { id: 33, name: "Healthcare" },
  { id: 34, name: "Learnpress" },
  { id: 35, name: "Meat Shop" },
  { id: 36, name: "Medical" },
  { id: 37, name: "Medical Prevention" },
  { id: 38, name: "Meetup" },
  { id: 39, name: "Mobile Apps" },
  { id: 40, name: "Music" },
  { id: 41, name: "News" },
  { id: 42, name: "Nonprofit" },
  { id: 43, name: "Onepage" },
  { id: 44, name: "Online Course" },
  { id: 45, name: "Personal Blog" },
  { id: 46, name: "Portfolio" },
  { id: 47, name: "Pregnancy" },
  { id: 48, name: "Premium" },
  { id: 49, name: "PSD" },
  { id: 50, name: "Religion" },
  { id: 51, name: "Restaurants" },
  { id: 52, name: "School" },
  { id: 53, name: "SEO" },
  { id: 54, name: "Software" },
  { id: 55, name: "Startups" },
  { id: 56, name: "University" },
  { id: 57, name: "Vcard" },
  { id: 58, name: "WooCommerce" },
  { id: 59, name: "Yoga" },
  { id: 60, name: "Magazine" },
  { id: 61, name: "Event" },
];
